spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobradar
    username: jobradar
    password: jobradar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jobradar:
  connector:
    html:
      url: https://jobs.lever.co/proper